listen = ":8888"

[database]
userName  = "postgres"
password  = "123456"
ipAddress = "localhost"
port      = 5432
dbName    = "db_novel"

[redis]
ipAddress   = "localhost:6379"
password    = ""
db          = 0